In [2]:
#packages
import os
import psycopg2
import json
import git
import pandas as pd

In [3]:
# Aggre Transaction Details

Path1="D:/Phone pay/pulse/data/aggregated/transaction/country/india/state/"
agg_trans_list=os.listdir(Path1)

column1={'States':[], 'Years':[],'Quarter':[],'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

for state in agg_trans_list:
    state_1=Path1+state+"/"
    Agg_yr=os.listdir(state_1)
    for years in Agg_yr:
        years_1=state_1+years+"/"
        Agg_yr_list=os.listdir(years_1)
        for file in Agg_yr_list:
            file_1=years_1+file
            Data=open(file_1,'r')
            D=json.load(Data)
            for z in D['data']['transactionData']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              column1['Transaction_type'].append(Name)
              column1['Transaction_count'].append(count)
              column1['Transaction_amount'].append(amount)
              column1['States'].append(state)
              column1['Years'].append(years)
              column1['Quarter'].append(int(file.strip('.json')))
#Succesfully created a dataframe
Agg_Trans=pd.DataFrame(column1)

Agg_Trans["States"] = Agg_Trans["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Agg_Trans["States"] = Agg_Trans["States"].str.replace("-"," ")
Agg_Trans["States"] = Agg_Trans["States"].str.title()
Agg_Trans['States'] = Agg_Trans['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [4]:
# Aggre user details

Path2="D:/Phone pay/pulse/data/aggregated/user/country/india/state/"
Agg_user_list=os.listdir(Path2)

column2={'States':[], 'Years':[],'Quarter':[],'Brands':[], 'Transaction_count':[], 'Percentage':[]}

for state in Agg_user_list:
    state_2=Path2+state+"/"
    Agg_yr=os.listdir(state_2)
    for years in Agg_yr:
        years_2=state_2+years+"/"
        Agg_yr_list=os.listdir(years_2)
        for file in Agg_yr_list:
            file_2=years_2+file
            Data2=open(file_2,"r")
            E=json.load(Data2)

            try:
                for z in E['data']['usersByDevice']:
                    brands=z['brand']
                    count=z['count']
                    percentage=z['percentage']
                    column2['Brands'].append(brands)
                    column2['Transaction_count'].append(count)
                    column2['Percentage'].append(percentage)
                    column2['States'].append(state)
                    column2['Years'].append(years)
                    column2['Quarter'].append(int(file.strip('.json')))

            except:
                pass

Agg_user=pd.DataFrame(column2)

Agg_user["States"] = Agg_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Agg_user["States"] = Agg_user["States"].str.replace("-"," ")
Agg_user["States"] = Agg_user["States"].str.title()
Agg_user['States'] = Agg_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [5]:
# Aggregate insurance

Path3="D:/Phone pay/pulse/data/aggregated/insurance/country/india/state/"
Agg_insur_list=os.listdir(Path3)

column3= {"States":[], "Years":[], "Quarter":[], "Insurance_type":[], "Insurance_count":[],"Insurance_amount":[] }

for state in Agg_insur_list:
    state_3=Path3+state+"/"
    Agg_yr=os.listdir(state_3)
    for years in Agg_yr:
        years_3=state_3+years+"/"
        Agg_yr_list=os.listdir(years_3)
        for file in Agg_yr_list:
            file_3=years_3+file
            Data3=open(file_3,"r")
            F=json.load(Data3)

            
            for i in F["data"]["transactionData"]:
                Name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                column3["Insurance_type"].append(Name)
                column3["Insurance_count"].append(count)
                column3["Insurance_amount"].append(amount)
                column3["States"].append(state)
                column3["Years"].append(years)
                column3["Quarter"].append(int(file.strip(".json")))

Agg_insur=pd.DataFrame(column3)

Agg_insur["States"] = Agg_insur["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Agg_insur["States"] = Agg_insur["States"].str.replace("-"," ")
Agg_insur["States"] = Agg_insur["States"].str.title()
Agg_insur['States'] = Agg_insur['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [6]:
#Map Transaction

Path4="D:/Phone pay/pulse/data/map/transaction/hover/country/india/state/"
Map_tran_list=os.listdir(Path4)

column4={'States':[], 'Years':[],'Quarter':[],'District':[], 'Transaction_count':[], 'Transaction_amount':[]}

for state in Map_tran_list:
    state_4=Path4+state+"/"
    Map_yr=os.listdir(state_4)
    for years in Map_yr:
        years_4=state_4+years+"/"
        Map_yr_list=os.listdir(years_4)
        for file in Map_yr_list:
            file_4=years_4+file
            Data4=open(file_4,"r")
            J=json.load(Data4)
            
            for z in J['data']['hoverDataList']:
              Name=z['name']
              count=z['metric'][0]['count']
              amount=z['metric'][0]['amount']
              column4['District'].append(Name)
              column4['Transaction_count'].append(count)
              column4['Transaction_amount'].append(amount)
              column4['States'].append(state)
              column4['Years'].append(years)
              column4['Quarter'].append(int(file.strip('.json')))  

Map_trans=pd.DataFrame(column4)

Map_trans["States"] = Map_trans["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Map_trans["States"] =Map_trans["States"].str.replace("-"," ")
Map_trans["States"] = Map_trans["States"].str.title()
Map_trans['States'] = Map_trans['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [7]:
#Map users

Path5="D:/Phone pay/pulse/data/map/user/hover/country/india/state/"
Map_user_list=os.listdir(Path5)

column5={"States":[], "Years":[], "Quarter":[], "District":[], "RegisteredUser":[], "AppOpens":[]}
for state in Map_user_list:
    state_5=Path5+state+"/"
    Map_yr=os.listdir(state_5)
    for years in Map_yr:
        years_5=state_5+years+"/"
        Map_yr_list=os.listdir(years_5)
        for file in Map_yr_list:
            file_5=years_5+file
            Data5=open(file_5,"r")
            K=json.load(Data5)

            for i in K["data"]["hoverData"].items():
                district = i[0]
                registereduser = i[1]["registeredUsers"]
                appopens = i[1]["appOpens"]
                column5["District"].append(district)
                column5["RegisteredUser"].append(registereduser)
                column5["AppOpens"].append(appopens)
                column5["States"].append(state)
                column5["Years"].append(years)
                column5["Quarter"].append(int(file.strip(".json")))



Map_users=pd.DataFrame(column5)

Map_users["States"] = Map_users["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Map_users["States"] = Map_users["States"].str.replace("-"," ")
Map_users["States"] = Map_users["States"].str.title()
Map_users['States'] = Map_users['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [8]:
#Map Insurence

Path6="D:/Phone pay/pulse/data/map/insurance/hover/country/india/state/"
Map_insur_list=os.listdir(Path6)

column6= {"States":[], "Years":[], "Quarter":[], "District":[], "Transaction_count":[],"Transaction_amount":[] }

for state in Agg_insur_list:
    state_6=Path6+state+"/"
    Agg_yr=os.listdir(state_6)
    for years in Agg_yr:
        years_6=state_6+years+"/"
        Agg_yr_list=os.listdir(years_6)
        for file in Agg_yr_list:
            file_6=years_6+file
            Data6=open(file_6,"r")
            G=json.load(Data6)

            
            for i in G["data"]["hoverDataList"]:
                    name = i["name"]
                    count = i["metric"][0]["count"]
                    amount = i["metric"][0]["amount"]
                    column6["District"].append(name)
                    column6["Transaction_count"].append(count)
                    column6["Transaction_amount"].append(amount)
                    column6["States"].append(state)
                    column6["Years"].append(years)
                    column6["Quarter"].append(int(file.strip(".json")))

Map_insur=pd.DataFrame(column6)

Map_insur["States"] = Map_insur["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Map_insur["States"] = Map_insur["States"].str.replace("-"," ")
Map_insur["States"] = Map_insur["States"].str.title()
Map_insur['States'] = Map_insur['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [9]:
#Top Transaction

Path7="D:/Phone pay/pulse/data/top/transaction/country/india/state/"
Top_tran_list=os.listdir(Path7)

column7={"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in Top_tran_list:
    state_7=Path7+state+"/"
    Top_yr=os.listdir(state_7)
    for years in Top_yr:
        years_7=state_7+years+"/"
        Top_yr_list=os.listdir(years_7)
        for file in Top_yr_list:
            file_7=years_7+file
            Data7=open(file_7,"r")
            H=json.load(Data7)
            
            for i in H["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                column7["Pincodes"].append(entityName)
                column7["Transaction_count"].append(count)
                column7["Transaction_amount"].append(amount)
                column7["States"].append(state)
                column7["Years"].append(years)
                column7["Quarter"].append(int(file.strip(".json")))  

Top_trans=pd.DataFrame(column7)

Top_trans["States"] = Top_trans["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Top_trans["States"] = Top_trans["States"].str.replace("-"," ")
Top_trans["States"] = Top_trans["States"].str.title()
Top_trans['States'] = Top_trans['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [10]:
#Top users

Path8="D:/Phone pay/pulse/data/top/user/country/india/state/"
Top_user_list=os.listdir(Path8)

column8={"States":[], "Years":[], "Quarter":[], "Pincodes":[], "RegisteredUser":[]}

for state in Top_user_list:
    state_8=Path8+state+"/"
    Map_yr=os.listdir(state_8)
    for years in Map_yr:
        years_8=state_8+years+"/"
        Map_yr_list=os.listdir(years_8)
        for file in Map_yr_list:
            file_8=years_8+file
            Data8=open(file_8,"r")
            S=json.load(Data8)

            for i in S["data"]["pincodes"]:
                name = i["name"]
                registeredusers = i["registeredUsers"]
                column8["Pincodes"].append(name)
                column8["RegisteredUser"].append(registeredusers)
                column8["States"].append(state)
                column8["Years"].append(years)
                column8["Quarter"].append(int(file.strip(".json")))


Top_users=pd.DataFrame(column8)

Top_users["States"] = Top_users["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Top_users["States"] = Top_users["States"].str.replace("-"," ")
Top_users["States"] = Top_users["States"].str.title()
Top_users['States'] = Top_users['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [11]:
#Top Insurence

Path9="D:/Phone pay/pulse/data/top/insurance/country/india/state/"
Top_insur_list=os.listdir(Path9)

column9= {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in Top_insur_list:
    state_9=Path9+state+"/"
    Agg_yr=os.listdir(state_9)
    for years in Agg_yr:
        years_9=state_9+years+"/"
        Agg_yr_list=os.listdir(years_9)
        for file in Agg_yr_list:
            file_9=years_9+file
            Data9=open(file_9,"r")
            P=json.load(Data9)

            
            for i in P["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                column9["Pincodes"].append(entityName)
                column9["Transaction_count"].append(count)
                column9["Transaction_amount"].append(amount)
                column9["States"].append(state)
                column9["Years"].append(years)
                column9["Quarter"].append(int(file.strip(".json")))


Top_insur=pd.DataFrame(column9)

Top_insur["States"] =Top_insur["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
Top_insur["States"] = Top_insur["States"].str.replace("-"," ")
Top_insur["States"] = Top_insur["States"].str.title()
Top_insur['States'] = Top_insur['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [12]:
#Table Creation
#pgsql connection

mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        password = "shanlee",
                        database = "Phonepay_project",
                        port = "5432"
                        )
cursor = mydb.cursor()


#aggregated insurance table
create_query7= '''CREATE TABLE if not exists aggregated_insurance (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Insurance_type varchar(50),
                                                                      Insurance_count bigint,
                                                                      Insurance_amount bigint
                                                                      )'''
cursor.execute(create_query7)
mydb.commit()

for index,row in Agg_insur.iterrows():
    insert_query7 = '''INSERT INTO aggregated_insurance (States, Years, Quarter, Insurance_type, Insurance_count, Insurance_amount)
                                                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Insurance_type"],
              row["Insurance_count"],
              row["Insurance_amount"]
              )
    cursor.execute(insert_query7,values)
    mydb.commit()

    #aggregated transaction table
create_query1 = '''CREATE TABLE if not exists aggregated_transaction (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Transaction_type varchar(50),
                                                                      Transaction_count bigint,
                                                                      Transaction_amount bigint
                                                                      )'''
cursor.execute(create_query1)
mydb.commit()

for index,row in Agg_Trans.iterrows():
    insert_query1 = '''INSERT INTO aggregated_transaction (States, Years, Quarter, Transaction_type, Transaction_count, Transaction_amount)
                                                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Transaction_type"],
              row["Transaction_count"],
              row["Transaction_amount"]
              )
    cursor.execute(insert_query1,values)
    mydb.commit()


#aggregated user table
create_query2 = '''CREATE TABLE if not exists aggregated_user (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                Brands varchar(50),
                                                                Transaction_count bigint,
                                                                Percentage float)'''
cursor.execute(create_query2)
mydb.commit()

for index,row in Agg_user.iterrows():
    insert_query2 = '''INSERT INTO aggregated_user (States, Years, Quarter, Brands, Transaction_count, Percentage)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Brands"],
              row["Transaction_count"],
              row["Percentage"])
    cursor.execute(insert_query2,values)
    mydb.commit()


#map_insurance_table
create_query8 = '''CREATE TABLE if not exists map_insurance (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
cursor.execute(create_query8)
mydb.commit()

for index,row in Map_insur.iterrows():
            insert_query8 = '''
                INSERT INTO map_insurance (States, Years, Quarter, District, Transaction_count, Transaction_amount)
                VALUES (%s, %s, %s, %s, %s, %s)

            '''
            values = (
                row['States'],
                row['Years'],
                row['Quarter'],
                row['District'],
                row['Transaction_count'],
                row['Transaction_amount']
            )
            cursor.execute(insert_query8,values)
            mydb.commit()


#map_transaction_table
create_query3 = '''CREATE TABLE if not exists map_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
cursor.execute(create_query3)
mydb.commit()

for index,row in Map_trans.iterrows():
            insert_query3 = '''
                INSERT INTO map_Transaction (States, Years, Quarter, District, Transaction_count, Transaction_amount)
                VALUES (%s, %s, %s, %s, %s, %s)

            '''
            values = (
                row['States'],
                row['Years'],
                row['Quarter'],
                row['District'],
                row['Transaction_count'],
                row['Transaction_amount']
            )
            cursor.execute(insert_query3,values)
            mydb.commit()


#map_user_table
create_query4 = '''CREATE TABLE if not exists map_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        District varchar(50),
                                                        RegisteredUser bigint,
                                                        AppOpens bigint)'''

cursor.execute(create_query4)
mydb.commit()

for index,row in Map_users.iterrows():
    insert_query4 = '''INSERT INTO map_user (States, Years, Quarter, District, RegisteredUser, AppOpens)
                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["District"],
              row["RegisteredUser"],
              row["AppOpens"])
    cursor.execute(insert_query4,values)
    mydb.commit()


#top_insurance_table
create_query9 = '''CREATE TABLE if not exists top_insurance (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                Pincodes int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
cursor.execute(create_query9)
mydb.commit()

for index,row in Top_insur.iterrows():
    insert_query9 = '''INSERT INTO top_insurance (States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["Transaction_count"],
              row["Transaction_amount"])
    cursor.execute(insert_query9,values)
    mydb.commit()


#top_transaction_table
create_query5 = '''CREATE TABLE if not exists top_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                pincodes int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
cursor.execute(create_query5)
mydb.commit()

for index,row in Top_trans.iterrows():
    insert_query5 = '''INSERT INTO top_transaction (States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["Transaction_count"],
              row["Transaction_amount"])
    cursor.execute(insert_query5,values)
    mydb.commit()

#top_user_table
create_query6 = '''CREATE TABLE if not exists top_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        Pincodes int,
                                                        RegisteredUser bigint
                                                        )'''
cursor.execute(create_query6)
mydb.commit()

for index,row in Top_users.iterrows():
    insert_query6 = '''INSERT INTO top_user (States, Years, Quarter, Pincodes, RegisteredUser)
                                            values(%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["RegisteredUser"])
    cursor.execute(insert_query6,values)
    mydb.commit()

In [6]:
import json
import streamlit as st
import pandas as pd
import requests
import psycopg2
import plotly.express as px
import plotly.graph_objects as go
from streamlit_option_menu import option_menu

In [14]:
mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        password = "shanlee",
                        database = "Phonepay_project",
                        port = "5432"
                        )
cursor = mydb.cursor()

In [15]:
#Aggregated_insurance
cursor.execute("select * from aggregated_insurance;")
mydb.commit()
table7 = cursor.fetchall()

Aggre_insurance = pd.DataFrame(table7,columns = ("States", "Years", "Quarter", "Transaction_type", "Transaction_count","Transaction_amount"))

#Aggregated_transsaction
cursor.execute("select * from aggregated_transaction;")
mydb.commit()
table1 = cursor.fetchall()
Aggre_transaction = pd.DataFrame(table1,columns = ("States", "Years", "Quarter", "Transaction_type", "Transaction_count", "Transaction_amount"))

#Aggregated_user
cursor.execute("select * from aggregated_user")
mydb.commit()
table2 = cursor.fetchall()
Aggre_user = pd.DataFrame(table2,columns = ("States", "Years", "Quarter", "Brands", "Transaction_count", "Percentage"))

#Map_insurance
cursor.execute("select * from map_insurance")
mydb.commit()
table3 = cursor.fetchall()

Map_insurance = pd.DataFrame(table3,columns = ("States", "Years", "Quarter", "District", "Transaction_count","Transaction_amount"))

#Map_transaction
cursor.execute("select * from map_transaction")
mydb.commit()
table3 = cursor.fetchall()
Map_transaction = pd.DataFrame(table3,columns = ("States", "Years", "Quarter", "District", "Transaction_count", "Transaction_amount"))

#Map_user
cursor.execute("select * from map_user")
mydb.commit()
table4 = cursor.fetchall()
Map_user = pd.DataFrame(table4,columns = ("States", "Years", "Quarter", "District", "RegisteredUser", "AppOpens"))

#Top_insurance
cursor.execute("select * from top_insurance")
mydb.commit()
table5 = cursor.fetchall()

Top_insurance = pd.DataFrame(table5,columns = ("States", "Years", "Quarter", "Pincodes", "Transaction_count", "Transaction_amount"))

#Top_transaction
cursor.execute("select * from top_transaction")
mydb.commit()
table5 = cursor.fetchall()
Top_transaction = pd.DataFrame(table5,columns = ("States", "Years", "Quarter", "Pincodes", "Transaction_count", "Transaction_amount"))

#Top_user
cursor.execute("select * from top_user")
mydb.commit()
table6 = cursor.fetchall()
Top_user = pd.DataFrame(table6, columns = ("States", "Years", "Quarter", "Pincodes", "RegisteredUser"))

In [7]:
def Aggre_insurance_Y(df,year):
    aiy= df[df["Years"] == year]
    aiy.reset_index(drop= True, inplace= True)

    aiyg=aiy.groupby("States")[["Transaction_count", "Transaction_amount"]].sum()
    aiyg.reset_index(inplace= True)

    col1,col2= st.columns(2)
    with col1:

        fig_amount= px.bar(aiyg, x="States", y= "Transaction_amount",title= f"{year} TRANSACTION AMOUNT",
                           width=400, height= 600, color_discrete_sequence=px.colors.sequential.Aggrnyl)
        st.plotly_chart(fig_amount)
    with col2:

        fig_count= px.bar(aiyg, x="States", y= "Transaction_count",title= f"{year} TRANSACTION COUNT",
                          width=400, height= 600, color_discrete_sequence=px.colors.sequential.Bluered_r)
        st.plotly_chart(fig_count)

    col1,col2= st.columns(2)
    with col1:

        url= "https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson"
        response= requests.get(url)
        data1= json.loads(response.content)
        states_name_tra= [feature["properties"]["ST_NM"] for feature in data1["features"]]
        states_name_tra.sort()
        

        fig_india_1= px.choropleth(aiyg, geojson= data1, locations= "States", featureidkey= "properties.ST_NM",
                                 color= "Transaction_amount", color_continuous_scale= "Sunsetdark",
                                 range_color= (aiyg["Transaction_amount"].min(),aiyg["Transaction_amount"].max()),
                                 hover_name= "States",title = f"{year} TRANSACTION AMOUNT",
                                 fitbounds= "locations",width =400, height= 600)
        fig_india_1.update_geos(visible =False)
        
        st.plotly_chart(fig_india_1)

    with col2:

        fig_india_2= px.choropleth(aiyg, geojson= data1, locations= "States", featureidkey= "properties.ST_NM",
                                 color= "Transaction_count", color_continuous_scale= "Sunsetdark",
                                 range_color= (aiyg["Transaction_count"].min(),aiyg["Transaction_count"].max()),
                                 hover_name= "States",title = f"{year} TRANSACTION COUNT",
                                 fitbounds= "locations",width =400, height= 600)
        fig_india_2.update_geos(visible =False)
        
        st.plotly_chart(fig_india_2)

    return aiy

def Aggre_insurance_Y_Q(df,quarter):
    aiyq= df[df["Quarter"] == quarter]
    aiyq.reset_index(drop= True, inplace= True)

    aiyqg= aiyq.groupby("States")[["Transaction_count", "Transaction_amount"]].sum()
    aiyqg.reset_index(inplace= True)

    col1,col2= st.columns(2)

    with col1:
        fig_q_amount= px.bar(aiyqg, x= "States", y= "Transaction_amount", 
                            title= f"{aiyq['Years'].min()}  Q {quarter} TRANSACTION AMOUNT",width= 400, height=600,
                            color_discrete_sequence=px.colors.sequential.Burg_r)
        st.plotly_chart(fig_q_amount)

    with col2:
        fig_q_count= px.bar(aiyqg, x= "States", y= "Transaction_count", 
                            title= f"{aiyq['Years'].min()}  Q {quarter} TRANSACTION COUNT",width= 400, height=600,
                            color_discrete_sequence=px.colors.sequential.Cividis_r)
        st.plotly_chart(fig_q_count)

    col1,col2= st.columns(2)
    with col1:

        url= "https://gist.githubusercontent.com/jbrobst/56c13bbbf9d97d187fea01ca62ea5112/raw/e388c4cae20aa53cb5090210a42ebb9b765c0a36/india_states.geojson"
        response= requests.get(url)
        data1= json.loads(response.content)
        states_name_tra= [feature["properties"]["ST_NM"] for feature in data1["features"]]
        states_name_tra.sort()

        fig_india_1= px.choropleth(aiyqg, geojson= data1, locations= "States", featureidkey= "properties.ST_NM",
                                 color= "Transaction_amount", color_continuous_scale= "Sunsetdark",
                                 range_color= (aiyqg["Transaction_amount"].min(),aiyqg["Transaction_amount"].max()),
                                 hover_name= "States",title = f"{aiyq['Years'].min()}  Q {quarter} TRANSACTION AMOUNT",
                                 fitbounds= "locations",width =400, height= 600)
        fig_india_1.update_geos(visible =False)
        
        st.plotly_chart(fig_india_1)
    with col2:

        fig_india_2= px.choropleth(aiyqg, geojson= data1, locations= "States", featureidkey= "properties.ST_NM",
                                 color= "Transaction_count", color_continuous_scale= "Sunsetdark",
                                 range_color= (aiyqg["Transaction_count"].min(),aiyqg["Transaction_count"].max()),
                                 hover_name= "States",title = f"{aiyq['Years'].min()}  Q {quarter} TRANSACTION COUNT",
                                 fitbounds= "locations",width =400, height= 600)
        fig_india_2.update_geos(visible =False)
        
        st.plotly_chart(fig_india_2)
    
    return aiyq

def Aggre_Transaction_type(df, state):
    df_state= df[df["States"] == state]
    df_state.reset_index(drop= True, inplace= True)

    agttg= df_state.groupby("Transaction_type")[["Transaction_count", "Transaction_amount"]].sum()
    agttg.reset_index(inplace= True)

    col1,col2= st.columns(2)
    with col1:

        fig_hbar_1= px.bar(agttg, x= "Transaction_count", y= "Transaction_type", orientation="h",
                        color_discrete_sequence=px.colors.sequential.Aggrnyl, width= 400, 
                        title= f"{state.upper()} TRANSACTION TYPES AND TRANSACTION COUNT",height= 500)
        st.plotly_chart(fig_hbar_1)

    with col2:

        fig_hbar_2= px.bar(agttg, x= "Transaction_amount", y= "Transaction_type", orientation="h",
                        color_discrete_sequence=px.colors.sequential.Greens_r, width= 400,
                        title= f"{state.upper()} TRANSACTION TYPES AND TRANSACTION AMOUNT", height= 500)
        st.plotly_chart(fig_hbar_2)


def Aggre_user_plot_1(df,year):
    aguy= df[df["Years"] == year]
    aguy.reset_index(drop= True, inplace= True)
    
    aguyg= pd.DataFrame(aguy.groupby("Brands")["Transaction_count"].sum())
    aguyg.reset_index(inplace= True)

    fig_line_1= px.bar(aguyg, x="Brands",y= "Transaction_count", title=f"{year} BRANDS AND TRANSACTION COUNT",
                    width=800,color_discrete_sequence=px.colors.sequential.Magenta_r)
    st.plotly_chart(fig_line_1)

    return aguy

def Aggre_user_plot_2(df,quarter):
    auqs= df[df["Quarter"] == quarter]
    auqs.reset_index(drop= True, inplace= True)

    fig_pie_1= px.pie(data_frame=auqs, names= "Brands", values="Transaction_count", hover_data= "Percentage",
                      width=800,title=f"{quarter} QUARTER TRANSACTION COUNT PERCENTAGE",hole=0.5, color_discrete_sequence= px.colors.sequential.Magenta_r)
    st.plotly_chart(fig_pie_1)

    return auqs

def Aggre_user_plot_3(df,state):
    aguqy= df[df["States"] == state]
    aguqy.reset_index(drop= True, inplace= True)

    aguqyg= pd.DataFrame(aguqy.groupby("Brands")["Transaction_count"].sum())
    aguqyg.reset_index(inplace= True)

    fig_scatter_1= px.line(aguqyg, x= "Brands", y= "Transaction_count", markers= True,width=800)
    st.plotly_chart(fig_scatter_1)

In [8]:
def map_insure_plot_1(df,state):
    miys= df[df["States"] == state]
    miysg= miys.groupby("District")[["Transaction_count","Transaction_amount"]].sum()
    miysg.reset_index(inplace= True)

    col1,col2= st.columns(2)
    with col1:
        fig_map_bar_1= px.bar(miysg, x= "District", y= "Transaction_amount",
                              width=400, height=500, title= f"{state.upper()} DISTRICT TRANSACTION AMOUNT",
                              color_discrete_sequence= px.colors.sequential.Mint_r)
        st.plotly_chart(fig_map_bar_1)

    with col2:
        fig_map_bar_1= px.bar(miysg, x= "District", y= "Transaction_count",
                              width=400, height= 500, title= f"{state.upper()} DISTRICT TRANSACTION COUNT",
                              color_discrete_sequence= px.colors.sequential.Mint)
        
        st.plotly_chart(fig_map_bar_1)

def map_insure_plot_2(df,state):
    miys= df[df["States"] == state]
    miysg= miys.groupby("District")[["Transaction_count","Transaction_amount"]].sum()
    miysg.reset_index(inplace= True)

    col1,col2= st.columns(2)
    with col1:
        fig_map_pie_1= px.pie(miysg, names= "District", values= "Transaction_amount",
                              width=500, height=500, title= f"{state.upper()} DISTRICT TRANSACTION AMOUNT",
                              hole=0.5,color_discrete_sequence= px.colors.sequential.Mint_r)
        st.plotly_chart(fig_map_pie_1)

    with col2:
        fig_map_pie_1= px.pie(miysg, names= "District", values= "Transaction_count",
                              width=500, height= 500, title= f"{state.upper()} DISTRICT TRANSACTION COUNT",
                              hole=0.5,  color_discrete_sequence= px.colors.sequential.Oranges_r)
        
        st.plotly_chart(fig_map_pie_1)


def map_user_plot_1(df, year):
    muy= df[df["Years"] == year]
    muy.reset_index(drop= True, inplace= True)
    muyg= muy.groupby("States")[["RegisteredUser", "AppOpens"]].sum()
    muyg.reset_index(inplace= True)

    fig_map_user_plot_1= px.line(muyg, x= "States", y= ["RegisteredUser","AppOpens"], markers= True,
                                width=800,height=800,title= f"{year} REGISTERED USER AND APPOPENS", color_discrete_sequence= px.colors.sequential.Bluyl)
    st.plotly_chart(fig_map_user_plot_1)

    return muy

def map_user_plot_2(df, quarter):
    muyq= df[df["Quarter"] == quarter]
    muyq.reset_index(drop= True, inplace= True)
    muyqg= muyq.groupby("States")[["RegisteredUser", "AppOpens"]].sum()
    muyqg.reset_index(inplace= True)

    fig_map_user_plot_1= px.line(muyqg, x= "States", y= ["RegisteredUser","AppOpens"], markers= True,
                                title= f"{df['Years'].min()}, {quarter} QUARTER REGISTERED USER AND APPOPENS",
                                width= 800,height=800,color_discrete_sequence= px.colors.sequential.Blugrn)
    st.plotly_chart(fig_map_user_plot_1)

    return muyq

def map_user_plot_3(df, state):
    muyqs= df[df["States"] == state]
    muyqs.reset_index(drop= True, inplace= True)
    muyqsg= muyqs.groupby("District")[["RegisteredUser", "AppOpens"]].sum()
    muyqsg.reset_index(inplace= True)

    
    fig_map_user_plot_1= px.pie(muyqsg, values= "RegisteredUser",names= "District",width=500,height=500,
                                title= f"{state.upper()} REGISTERED USER",hole=0.5,
                                color_discrete_sequence= px.colors.sequential.Rainbow_r)
    st.plotly_chart(fig_map_user_plot_1)

In [9]:
def top_user_plot_1(df,year):
    tuy= df[df["Years"] == year]
    tuy.reset_index(drop= True, inplace= True)

    tuyg= pd.DataFrame(tuy.groupby(["States","Quarter"])["RegisteredUser"].sum())
    tuyg.reset_index(inplace= True)

    fig_top_plot_1= px.bar(tuyg, x= "States", y= "RegisteredUser", barmode= "group", color= "Quarter",
                            width=1000, height= 800, color_continuous_scale= px.colors.sequential.Rainbow)
    st.plotly_chart(fig_top_plot_1)

    return tuy

def top_user_plot_2(df,state):
    tuys= df[df["States"] == state]
    tuys.reset_index(drop= True, inplace= True)

    tuysg= pd.DataFrame(tuys.groupby("Quarter")["RegisteredUser"].sum())
    tuysg.reset_index(inplace= True)

    fig_top_plot_2= px.bar(tuys, x= "Quarter", y= "RegisteredUser",barmode= "group",
                           width=1000, height= 800,color= "Pincodes",hover_data="Pincodes",
                            color_continuous_scale= px.colors.sequential.Magenta)
    st.plotly_chart(fig_top_plot_2)

In [10]:
def ques1():
    brand= Aggre_user[["Brands","Transaction_count"]]
    brand1= brand.groupby("Brands")["Transaction_count"].sum().sort_values(ascending=False)
    brand2= pd.DataFrame(brand1).reset_index()

    fig_brands= px.pie(brand2, values= "Transaction_count", names= "Brands", color_discrete_sequence=px.colors.sequential.Rainbow_r,
                       title= "Top Mobile Brands of Transaction_count")
    return st.plotly_chart(fig_brands)

def ques2():
    lt= Aggre_transaction[["States", "Transaction_amount"]]
    lt1= lt.groupby("States")["Transaction_amount"].sum().sort_values(ascending= True)
    lt2= pd.DataFrame(lt1).reset_index().head(10)

    fig_lts= px.bar(lt2, x= "States", y= "Transaction_amount",title= "LOWEST TRANSACTION AMOUNT and STATES",
                    color_discrete_sequence= px.colors.sequential.Oranges_r)
    return st.plotly_chart(fig_lts)

def ques3():
    ht= Aggre_transaction[["States", "Transaction_amount"]]
    ht1= ht.groupby("States")["Transaction_amount"].sum().sort_values(ascending= False)
    ht2= pd.DataFrame(ht1).reset_index().head(10)

    fig_lts= px.bar(ht2, x= "States", y= "Transaction_amount",title= "HIGHEST TRANSACTION AMOUNT and STATES",
                    color_discrete_sequence= px.colors.sequential.Oranges_r)
    return st.plotly_chart(fig_lts)


def ques4():
    htd= Map_transaction[["District", "Transaction_amount"]]
    htd1= htd.groupby("District")["Transaction_amount"].sum().sort_values(ascending=False)
    htd2= pd.DataFrame(htd1).head(10).reset_index()

    fig_htd= px.bar(htd2, x= "Transaction_amount", y= "District", title="TOP 10 DISTRICT OF HIGHEST TRANSACTION AMOUNT",
                    color_discrete_sequence=px.colors.sequential.Reds)
    return st.plotly_chart(fig_htd)

def ques5():
    htd= Map_transaction[["District", "Transaction_amount"]]
    htd1= htd.groupby("District")["Transaction_amount"].sum().sort_values(ascending=True)
    htd2= pd.DataFrame(htd1).head(10).reset_index()

    fig_htd= px.bar(htd2, x= "Transaction_amount", y= "District", title="TOP 10 DISTRICT OF LOWEST TRANSACTION AMOUNT",
                    color_discrete_sequence=px.colors.sequential.Reds)
    return st.plotly_chart(fig_htd)


def ques6():
    sa= Map_user[["States", "AppOpens"]]
    sa1= sa.groupby("States")["AppOpens"].sum().sort_values(ascending=False)
    sa2= pd.DataFrame(sa1).reset_index().head(10)

    fig_sa= px.pie(sa2, names= "States", values= "AppOpens", title="Top 10 States With Phonepe users",hole=0.5,
                color_discrete_sequence= px.colors.sequential.Rainbow_r)
    return st.plotly_chart(fig_sa)

def ques7():
    sa= Map_user[["States", "AppOpens"]]
    sa1= sa.groupby("States")["AppOpens"].sum().sort_values(ascending=True)
    sa2= pd.DataFrame(sa1).reset_index().head(10)

    fig_sa= px.pie(sa2, names= "States", values= "AppOpens", title="lowest 10 States With Phonepe users",hole=0.5,
                color_discrete_sequence= px.colors.sequential.Rainbow_r)
    return st.plotly_chart(fig_sa)

def ques8():
    stc= Aggre_transaction[["States", "Transaction_count"]]
    stc1= stc.groupby("States")["Transaction_count"].sum().sort_values(ascending=True)
    stc2= pd.DataFrame(stc1).reset_index()

    fig_stc= px.bar(stc2, x= "States", y= "Transaction_count", title= "STATES WITH LOWEST TRANSACTION COUNT",
                    color_discrete_sequence= px.colors.sequential.Magenta_r)
    return st.plotly_chart(fig_stc)

def ques9():
    stc= Aggre_transaction[["States", "Transaction_count"]]
    stc1= stc.groupby("States")["Transaction_count"].sum().sort_values(ascending=False)
    stc2= pd.DataFrame(stc1).reset_index()

    fig_stc= px.bar(stc2, x= "States", y= "Transaction_count", title= "STATES WITH HIGHEST TRANSACTION COUNT",
                    color_discrete_sequence= px.colors.sequential.Magenta_r)
    return st.plotly_chart(fig_stc)


def ques10():
    dt= Map_transaction[["District", "Transaction_amount"]]
    dt1= dt.groupby("District")["Transaction_amount"].sum().sort_values(ascending=False)
    dt2= pd.DataFrame(dt1).reset_index().head(50)

    fig_dt= px.bar(dt2, x= "District", y= "Transaction_amount", title= "DISTRICT WITH HIGHEST TRANSACTION AMOUNT",
                color_discrete_sequence= px.colors.sequential.Viridis)
    return st.plotly_chart(fig_dt)

In [11]:
#Streamlit part

st.set_page_config(layout= "wide")

st.title(":orange[PHONEPE DATA VISUALIZATION AND EXPLORATION]")
st.write("")


with st.sidebar:


    select= option_menu("Main Menu",["Home", "Data Exploration", "Top Charts"])


if select == "Home":

    col1,col2= st.columns(2)

    with col1:
        st.header(":violet[PHONEPE]")
        st.subheader(":red[INDIA'S BEST TRANSACTION APP]")
        st.markdown(":violet[INDIA'S  DIGITAL PAYMENT PLATFORM] ")

        st.write("****:blue[FEATURES]****")
        st.write("****100% Secure and Lightining Fast****")
        st.write("****Instant Money Transfer****")
        st.write("****Transfer Money upto 1 Lakhs in a Day****")
        st.write("****Banking 24/7****")
        st.write("****Get Cash Back****")
        st.download_button("DOWNLOAD THE APP NOW", "https://www.phonepe.com/app-download/")
    with col2:
        st.video("C:\\Users\\shana\\.ipython\\Phonepay intro.mp4")

    col3,col4= st.columns(2)
    
    with col3:
        st.video("C:\\Users\\shana\\.ipython\\Phonepay ad.mp4")

    with col4:
        st.write("****Easy Transactions****")
        st.write("****One App For All Your Payments****")
        st.write("****Multiple Ways To Pay****")
        st.write("****1.Direct Transfer & More****")
        st.write("****2.QR Code****")
        st.write("****Earn Great Rewards****")

if select == "Data Exploration":
    tab1, tab2, tab3= st.tabs(["Aggregated Analysis", "Map Analysis", "Top Analysis"])

    with tab1:
        method = st.radio("**Select the Analysis Method**",["Insurance Analysis", "Transaction Analysis", "User Analysis"])

        if method == "Insurance Analysis":
            col1,col2= st.columns(2)
            with col1:
                years= st.selectbox("**Select the Year**", Aggre_insurance["Years"].unique())

            df_agg_insur_Y= Aggre_insurance_Y(Aggre_insurance,years)
            
            col1,col2= st.columns(2)
            with col1:
                quarters= st.selectbox("**Select the Quarter**", df_agg_insur_Y["Quarter"].unique())

            Aggre_insurance_Y_Q(df_agg_insur_Y, quarters)

            
        elif method == "Transaction Analysis":
            col1,col2= st.columns(2)
            with col1:
                years_at= st.selectbox("**Select the Year_ta**", Aggre_transaction["Years"].unique())

            df_agg_tran_Y= Aggre_insurance_Y(Aggre_transaction,years_at)
            
            col1,col2= st.columns(2)
            with col1:
                quarters_at= st.selectbox("**Select the Quarter_ta**", df_agg_tran_Y["Quarter"].unique())

            df_agg_tran_Y_Q= Aggre_insurance_Y_Q(df_agg_tran_Y, quarters_at)
            

            state_Y_Q= st.selectbox("**Select the State_ta**",df_agg_tran_Y_Q["States"].unique())

            Aggre_Transaction_type(df_agg_tran_Y_Q,state_Y_Q)


        elif method == "User Analysis":
            year_au= st.selectbox("Select the Year_au",Aggre_user["Years"].unique())
            agg_user_Y= Aggre_user_plot_1(Aggre_user,year_au)

            quarter_au= st.selectbox("Select the Quarter_au",agg_user_Y["Quarter"].unique())
            agg_user_Y_Q= Aggre_user_plot_2(agg_user_Y,quarter_au)

            state_au= st.selectbox("**Select the State_au**",agg_user_Y["States"].unique())
            Aggre_user_plot_3(agg_user_Y_Q,state_au)

    with tab2:
        method_map = st.radio("**Select the Analysis Method(MAP)**",["Map Insurance Analysis", "Map Transaction Analysis", "Map User Analysis"])

        if method_map == "Map Insurance Analysis":
            col1,col2= st.columns(2)
            with col1:
                years_m1= st.selectbox("**Select the Year_mi**", Map_insurance["Years"].unique())

            df_map_insur_Y= Aggre_insurance_Y(Map_insurance,years_m1)
            
            col1,col2= st.columns(2)
            with col1:
                quarters_m1= st.selectbox("**Select the Quarter_mi**", df_map_insur_Y["Quarter"].unique())

            df_map_insur_Y_Q= Aggre_insurance_Y_Q(df_map_insur_Y, quarters_m1)

            col1,col2= st.columns(2)
            with col1:
                state_m2= st.selectbox("Select the State_mi", df_map_insur_Y_Q["States"].unique())            
            
            map_insure_plot_2(df_map_insur_Y_Q, state_m2)

            col1,col2= st.columns(2)
            with col1:
                state_m1= st.selectbox("Select the State_District_Analyse", df_map_insur_Y["States"].unique())

            map_insure_plot_1(df_map_insur_Y,state_m1)

        elif method_map == "Map Transaction Analysis":
            col1,col2= st.columns(2)
            with col1:
                years_m2= st.selectbox("**Select the Year_mt**", Map_transaction["Years"].unique())

            df_map_tran_Y= Aggre_insurance_Y(Map_transaction, years_m2)
            
            col1,col2= st.columns(2)
            with col1:
                quarters_m2= st.selectbox("**Select the Quarter_mt**", df_map_tran_Y["Quarter"].unique())

            df_map_tran_Y_Q= Aggre_insurance_Y_Q(df_map_tran_Y, quarters_m2)

            col1,col2= st.columns(2)
            with col1:
                state_m4= st.selectbox("Select the State_mt", df_map_tran_Y_Q["States"].unique())            
            
            map_insure_plot_2(df_map_tran_Y_Q, state_m4)

            col1,col2= st.columns(2)
            with col1:
                state_m3= st.selectbox("Select the State_District_Analyse_mt", df_map_tran_Y["States"].unique())

            map_insure_plot_1(df_map_tran_Y,state_m3)

        elif method_map == "Map User Analysis":
            col1,col2= st.columns(2)
            with col1:
                year_mu1= st.selectbox("**Select the Year_mu**",Map_user["Years"].unique())
            map_user_Y= map_user_plot_1(Map_user, year_mu1)

            col1,col2= st.columns(2)
            with col1:
                quarter_mu1= st.selectbox("**Select the Quarter_mu**",map_user_Y["Quarter"].unique())
            map_user_Y_Q= map_user_plot_2(map_user_Y,quarter_mu1)

            col1,col2= st.columns(2)
            with col1:
                state_mu1= st.selectbox("**Select the State_mu**",map_user_Y_Q["States"].unique())
            map_user_plot_3(map_user_Y_Q, state_mu1)

    with tab3:
        method_top = st.radio("**Select the Analysis Method(TOP)**",["Top Insurance Analysis", "Top Transaction Analysis", "Top User Analysis"])

        if method_top == "Top Insurance Analysis":
            col1,col2= st.columns(2)
            with col1:
                years_t1= st.selectbox("**Select the Year_ti**", Top_insurance["Years"].unique())
 
            df_top_insur_Y= Aggre_insurance_Y(Top_insurance,years_t1)

            
            col1,col2= st.columns(2)
            with col1:
                quarters_t1= st.selectbox("**Select the Quarter_ti**", df_top_insur_Y["Quarter"].unique())

            df_top_insur_Y_Q= Aggre_insurance_Y_Q(df_top_insur_Y, quarters_t1)

        
        elif method_top == "Top Transaction Analysis":
            col1,col2= st.columns(2)
            with col1:
                years_t2= st.selectbox("**Select the Year_tt**", Top_transaction["Years"].unique())
 
            df_top_tran_Y= Aggre_insurance_Y(Top_transaction,years_t2)

            
            col1,col2= st.columns(2)
            with col1:
                quarters_t2= st.selectbox("**Select the Quarter_tt**", df_top_tran_Y["Quarter"].unique())

            df_top_tran_Y_Q= Aggre_insurance_Y_Q(df_top_tran_Y, quarters_t2)

        elif method_top == "Top User Analysis":
            col1,col2= st.columns(2)
            with col1:
                years_t3= st.selectbox("**Select the Year_tu**", Top_user["Years"].unique())

            df_top_user_Y= top_user_plot_1(Top_user,years_t3)

            col1,col2= st.columns(2)
            with col1:
                state_t3= st.selectbox("**Select the State_tu**", df_top_user_Y["States"].unique())

            df_top_user_Y_S= top_user_plot_2(df_top_user_Y,state_t3)


if select == "Top Charts":

    ques= st.selectbox("**Select the Question**",('Top Brands Of Mobiles Used','States With Lowest Trasaction Amount','States With Highest Trasaction Amount',
                                  'District With Highest Transaction Amount','District With Lowest Transaction Amount',
                                  'Top 10 States With Phonepe users','Least 10 States With Phonepe users','States With Lowest Trasaction Count',
                                 'States With Highest Trasaction Count',
                                 'Top 50 District With Highest Transaction Amount'))
    
    if ques=="Top Brands Of Mobiles Used":
        ques1()

    elif ques=="States With Lowest Trasaction Amount":
        ques2()

    elif ques=="States With Highest Trasaction Amount":
        ques3()

    elif ques=="District With Highest Transaction Amount":
        ques4()

    elif ques=="District With Lowest Transaction Amount":
        ques5()

    elif ques=="Top 10 States With Phonepe users":
        ques6()

    elif ques=="Least 10 States With Phonepe users":
        ques7()

    elif ques=="States With Lowest Trasaction Count":
        ques8()

    elif ques=="States With Highest Trasaction Count":
        ques9()


    elif ques=="Top 50 District With Highest Transaction Amount":
        ques10()

2024-01-16 18:14:17.175 Session state does not function when running a script without `streamlit run`